#pragma once

#include "aoe/macro/count.h"
#include <type_traits>

/**
 * @brief 拼接多个名称，成为一个新的名称
 */
#define AOE_CONCAT(...) AOE_DETAILS_CONCAT_CALLER(AOE_DETAILS_CONCAT_, AOE_COUNT_ARGS(__VA_ARGS__))(__VA_ARGS__)

// 拼接函数的辅助函数，确保x参数和y参数在拼接之前充分展开
#define AOE_DETAILS_CONCAT(x, y)        x##y
#define AOE_DETAILS_CONCAT_CALLER(x, y) AOE_DETAILS_CONCAT(x, y)

// 不同参数数量的宏实现
#define AOE_DETAILS_CONCAT_2(x, y)    AOE_DETAILS_CONCAT_CALLER(x, y)
#define AOE_DETAILS_CONCAT_3(x, ...)  AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_2(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_4(x, ...)  AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_3(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_5(x, ...)  AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_4(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_6(x, ...)  AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_5(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_7(x, ...)  AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_6(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_8(x, ...)  AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_7(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_9(x, ...)  AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_8(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_10(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_9(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_11(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_10(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_12(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_11(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_13(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_12(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_14(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_13(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_15(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_14(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_16(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_15(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_17(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_16(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_18(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_17(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_19(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_18(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_20(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_19(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_21(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_20(__VA_ARGS__))
#define AOE_DETAILS_CONCAT_22(x, ...) AOE_DETAILS_CONCAT_CALLER(x, AOE_DETAILS_CONCAT_21(__VA_ARGS__))
